// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HelthCareProject.Models;

[Index("PrescriptionId", Name = "fk_appointments_prescription")]
[Index("AppointmentDate", Name = "idx_appointments_date")]
[Index("DoctorId", Name = "idx_appointments_doctor")]
[Index("DoctorId", "AppointmentDate", Name = "idx_appointments_doctordate")]
[Index("PatientId", Name = "idx_appointments_patient")]
[Index("PatientId", "AppointmentDate", Name = "idx_appointments_patientdate")]
[Index("ReexaminationDate", Name = "idx_appointments_reexaminationdate")]
public partial class appointment
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AppointmentDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ReexaminationDate { get; set; }

    public int? DoctorId { get; set; }

    public int? PatientId { get; set; }

    public int? PrescriptionId { get; set; }

    [ForeignKey("DoctorId")]
    [InverseProperty("appointments")]
    public virtual doctor Doctor { get; set; }

    [ForeignKey("PatientId")]
    [InverseProperty("appointments")]
    public virtual patient Patient { get; set; }

    [ForeignKey("PrescriptionId")]
    [InverseProperty("appointments")]
    public virtual prescription Prescription { get; set; }
}