// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HelthCareProject.Models;

[Index("DoctorId", Name = "idx_assistants_doctorid")]
[Index("UserId", Name = "idx_assistants_userid", IsUnique = true)]
public partial class assistant
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    public string UserId { get; set; }

    public int? DoctorId { get; set; }

    [ForeignKey("DoctorId")]
    [InverseProperty("assistants")]
    public virtual doctor Doctor { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("assistant")]
    public virtual user User { get; set; }
}