// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HelthCareProject.Models;

[Index("Timestamp", Name = "idx_chatbotmessages_timestamp")]
[Index("UserId", Name = "idx_chatbotmessages_userid")]
public partial class chatbotmessage
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "text")]
    public string Text { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Timestamp { get; set; }

    [Column(TypeName = "bit(1)")]
    public ulong? IsFromChatbot { get; set; }

    [StringLength(100)]
    public string UserId { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("chatbotmessages")]
    public virtual user User { get; set; }
}