// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HelthCareProject.Models;

[Index("title", Name = "idx_chats_title")]
public partial class chat
{
    [Key]
    public int Id { get; set; }

    [StringLength(20)]
    public string title { get; set; }

    [InverseProperty("Chat")]
    public virtual ICollection<message> messages { get; set; } = new List<message>();

    [ForeignKey("ChatId")]
    [InverseProperty("Chats")]
    public virtual ICollection<user> Users { get; set; } = new List<user>();
}