// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HelthCareProject.Models;

[Index("ClinicId", Name = "fk_clinicaddresses_clinic")]
[Index("Latitude", "Longitude", Name = "idx_clinicaddresses_location")]
[Index("StreetName", Name = "idx_clinicaddresses_streetname")]
public partial class clinicaddress
{
    [Key]
    public int Id { get; set; }

    [StringLength(10)]
    public string BuildingNumber { get; set; }

    [StringLength(100)]
    public string StreetName { get; set; }

    [StringLength(10)]
    public string Floor { get; set; }

    [StringLength(10)]
    public string ApartmentNumber { get; set; }

    public float? Latitude { get; set; }

    public float? Longitude { get; set; }

    public int? ClinicId { get; set; }

    [ForeignKey("ClinicId")]
    [InverseProperty("clinicaddresses")]
    public virtual clinic Clinic { get; set; }

    [InverseProperty("ClinicAddress")]
    public virtual ICollection<clinic> clinics { get; set; } = new List<clinic>();
}