// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HelthCareProject.Models;

[Index("ClinicAddressId", Name = "fk_clinics_address")]
[Index("DoctorId", Name = "idx_clinics_doctor")]
[Index("GovernorateId", Name = "idx_clinics_governorate")]
[Index("OpeningTime", "ClosingTime", Name = "idx_clinics_hours")]
[Index("Name", Name = "idx_clinics_name")]
public partial class clinic
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(15)]
    public string PhoneNumber { get; set; }

    public int? Examination { get; set; }

    [Column(TypeName = "time")]
    public TimeOnly? OpeningTime { get; set; }

    [Column(TypeName = "time")]
    public TimeOnly? ClosingTime { get; set; }

    [Column(TypeName = "time")]
    public TimeOnly? SlotDuration { get; set; }

    [StringLength(250)]
    public string Description { get; set; }

    public int? ClinicAddressId { get; set; }

    public int? DoctorId { get; set; }

    public int? GovernorateId { get; set; }

    [ForeignKey("ClinicAddressId")]
    [InverseProperty("clinics")]
    public virtual clinicaddress ClinicAddress { get; set; }

    [ForeignKey("DoctorId")]
    [InverseProperty("clinics")]
    public virtual doctor Doctor { get; set; }

    [ForeignKey("GovernorateId")]
    [InverseProperty("clinics")]
    public virtual governorate Governorate { get; set; }

    [InverseProperty("Clinic")]
    public virtual ICollection<appointmentslot> appointmentslots { get; set; } = new List<appointmentslot>();

    [InverseProperty("Clinic")]
    public virtual ICollection<clinicaddress> clinicaddresses { get; set; } = new List<clinicaddress>();
}