// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HelthCareProject.Models;

[Table("governorate")]
[Index("Name", Name = "idx_governorate_name")]
public partial class governorate
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    [InverseProperty("Governorate")]
    public virtual ICollection<clinic> clinics { get; set; } = new List<clinic>();

    [InverseProperty("Governorate")]
    public virtual ICollection<doctor> doctors { get; set; } = new List<doctor>();
}