// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HelthCareProject.Models;

[Index("FileName", Name = "idx_medicalhistoryrecords_filename")]
[Index("PatientId", Name = "idx_medicalhistoryrecords_patient")]
[Index("UploadDate", Name = "idx_medicalhistoryrecords_uploaddate")]
public partial class medicalhistoryrecord
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string FileName { get; set; }

    public byte[] FileData { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UploadDate { get; set; }

    public int? PatientId { get; set; }

    [ForeignKey("PatientId")]
    [InverseProperty("medicalhistoryrecords")]
    public virtual patient Patient { get; set; }
}