// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HelthCareProject.Models;

[Index("ChatId", Name = "idx_messages_chat")]
[Index("ChatId", "SentAt", Name = "idx_messages_chattime")]
[Index("DoctorId", Name = "idx_messages_doctor")]
[Index("PatientId", Name = "idx_messages_patient")]
[Index("SentAt", Name = "idx_messages_sentat")]
[Index("UserId", Name = "idx_messages_user")]
public partial class message
{
    [Key]
    public int Id { get; set; }

    [StringLength(30)]
    public string Content { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SentAt { get; set; }

    public int? ChatId { get; set; }

    public int? PatientId { get; set; }

    public int? DoctorId { get; set; }

    [StringLength(100)]
    public string UserId { get; set; }

    [ForeignKey("ChatId")]
    [InverseProperty("messages")]
    public virtual chat Chat { get; set; }

    [ForeignKey("DoctorId")]
    [InverseProperty("messages")]
    public virtual doctor Doctor { get; set; }

    [ForeignKey("PatientId")]
    [InverseProperty("messages")]
    public virtual patient Patient { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("messages")]
    public virtual user User { get; set; }
}