// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HelthCareProject.Models;

[Index("CreatedAt", Name = "idx_notifications_createdat")]
[Index("IsRead", Name = "idx_notifications_isread")]
[Index("UserId", Name = "idx_notifications_userid")]
public partial class notification
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "text")]
    public string Message { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "bit(1)")]
    public ulong? IsRead { get; set; }

    [StringLength(100)]
    public string UserId { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("notifications")]
    public virtual user User { get; set; }
}