// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HelthCareProject.Models;

[Index("UserId", Name = "idx_patients_userid", IsUnique = true)]
public partial class patient
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    public string UserId { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("patient")]
    public virtual user User { get; set; }

    [InverseProperty("Patient")]
    public virtual ICollection<appointment> appointments { get; set; } = new List<appointment>();

    [InverseProperty("Patient")]
    public virtual ICollection<medicalhistoryrecord> medicalhistoryrecords { get; set; } = new List<medicalhistoryrecord>();

    [InverseProperty("Patient")]
    public virtual ICollection<message> messages { get; set; } = new List<message>();

    [InverseProperty("Patient")]
    public virtual ICollection<patientdoctor> patientdoctors { get; set; } = new List<patientdoctor>();

    [InverseProperty("Patient")]
    public virtual ICollection<prescription> prescriptions { get; set; } = new List<prescription>();
}