// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HelthCareProject.Models;

[Table("patientdoctor")]
[Index("DoctorId", Name = "idx_patientdoctor_doctor")]
[Index("PatientId", "DoctorId", Name = "unique_patient_doctor", IsUnique = true)]
public partial class patientdoctor
{
    [Key]
    public int Id { get; set; }

    public int? PatientId { get; set; }

    public int? DoctorId { get; set; }

    [ForeignKey("DoctorId")]
    [InverseProperty("patientdoctors")]
    public virtual doctor Doctor { get; set; }

    [ForeignKey("PatientId")]
    [InverseProperty("patientdoctors")]
    public virtual patient Patient { get; set; }
}