// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HelthCareProject.Models;

[Index("PatientId", Name = "idx_prescriptions_patient")]
public partial class prescription
{
    [Key]
    public int Id { get; set; }

    public byte[] file { get; set; }

    public int? PatientId { get; set; }

    [ForeignKey("PatientId")]
    [InverseProperty("prescriptions")]
    public virtual patient Patient { get; set; }

    [InverseProperty("Prescription")]
    public virtual ICollection<appointment> appointments { get; set; } = new List<appointment>();
}