// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HelthCareProject.Models;

[Index("ClaimType", Name = "idx_roleclaims_claimtype")]
[Index("RoleId", Name = "idx_roleclaims_roleid")]
public partial class roleclaim
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    public string RoleId { get; set; }

    [StringLength(250)]
    public string ClaimType { get; set; }

    [StringLength(250)]
    public string ClaimValue { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("roleclaims")]
    public virtual role Role { get; set; }
}