// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HelthCareProject.Models;

[Index("Name", Name = "idx_roles_name")]
public partial class role
{
    [Key]
    [StringLength(100)]
    public string Id { get; set; }

    [StringLength(250)]
    public string Name { get; set; }

    [InverseProperty("Role")]
    public virtual ICollection<roleclaim> roleclaims { get; set; } = new List<roleclaim>();

    [ForeignKey("RoleId")]
    [InverseProperty("Roles")]
    public virtual ICollection<user> Users { get; set; } = new List<user>();
}