// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HelthCareProject.Models;

[Index("ClaimType", Name = "idx_userclaims_claimtype")]
[Index("UserId", Name = "idx_userclaims_userid")]
public partial class userclaim
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    public string UserId { get; set; }

    [StringLength(250)]
    public string ClaimType { get; set; }

    [StringLength(250)]
    public string ClaimValue { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("userclaims")]
    public virtual user User { get; set; }
}